### ISSUE TITLE
I have some problems !

### ISSUE THREAD

**Issue by X901** [sunlubo/StretchyHeaderView#2]
Hi ,
I really appreciated your work , i was searching a lot and finally I find your library 
Anyway I have two problems

**1.** The image is not scaleAspectFill ,
I tried to modify your code but still even when add 
`cover.contentMode = .scaleAspectFill
`
The image not fit correctly , it's looks like the image zoom in

![alt tag](http://i.imgur.com/CFIwUeu.jpg)

**2.** for some reason I have transparent Navigation bar , not solid color like in your gif 
I want to have solid color without transparent

![alt tag](http://i.imgur.com/kX3AUsd.png)

**Comment by sunlubo** [comment]
1. The original effect is 'zoom in', you can modify `ScalableCover.layoutSubviews` to achieve your expected effect.

2. For this, you can modify `UINavigationBar.updateAlpha` to achieve your expected effect.

**Comment by X901** [comment]
Thank you very much , I will give it a try .
BTW The library need to be updated to support Swift 3 , it take me a while to make it work in swift 3

**Comment by sunlubo** [comment]
OK, If I have space time today, I will update it to support Swift 3.

**Comment by HenryHins** [comment]
@X901 Hey I am having the same alpha problem you were having. Changing `updateAlpha` didn't do anything. How did you solve it? Thanks!
